environment:
  nodejs_version: "6.9.1"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - npm run dist:win

test_script:
  - npm test

artifacts: 
  - path: ./dist/bingo-electron Setup *.exe
    name: bingosetup

deploy:
  description: 'automatic appveyor deploy'
  provider: GitHub
  auth_token:
    secure: oKEM3xVHhwJWuMKJFGYfo39b7t7N8LhCCktM2qzxLzKFaAbHnOIvns/LL4ndDDPQ
  artifact: bingosetup
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

notifications:
  - provider: Slack
    incoming_webhook:
      secure: yH5F7E9Y/9Oxdha+OVmuhVcPiqTOOSP3+Y1Tl7viZjLPoKav3euob5O5H6Td3zBXTmXx3d3P8zdQWSsfMwWpgTo1zAt2ed9D56FC2RYyCMw=
    channel: appveyor

