environment:
  nodejs_version: "6.9.1"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - npm run dist:win

test_script:
  - npm test

notifications:
  - provider: Slack
    incoming_webhook:
      secure: $env:slack
    channel: development

