environment:
  nodejs_version: "6.9.1"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - npm run dist:win

test_script:
  - npm test

deploy:
  provider: GitHub
  auth_token:
    secure: %GH_TOKEN%
  artifact: ./dist/bingo-electron Setup *.exe
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true

notifications:
  - provider: Slack
    incoming_webhook:
      secure: %SLACK%
    channel: development

